dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'

networks:
  # default: mainnet-fork  # alchemy
  # default: ganache-local
  default: development
  development:
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000
  ganache-local:
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000  
  rinkeby:
    # https://docs.chain.link/docs/vrf-contracts/v1/#rinkeby # tutor version
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'   

    #https://docs.chain.link/docs/vrf-contracts/  Rinkeby testnet  V2
    # vrf_coordinator: 0x6168499c0cFfCaCD319c818142124B7A15E857ab  

    #https://docs.chain.link/docs/ethereum-addresses/    Kovan Testnet and  ETH / USD
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'   

    #https://docs.chain.link/docs/link-token-contracts/
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'

    #https://docs.chain.link/docs/vrf-contracts/v1/#rinkeby 
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000
    verify: True

  kovan:
    # https://docs.chain.link/docs/vrf-contracts/v1/#kovan # tutor version
    vrf_coordinator: '0xdD3782915140c8f3b190B5D67eAc6dc5760C46E9'   


    #https://docs.chain.link/docs/ethereum-addresses/    Kovan Testnet and  ETH / USD
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'   

    #https://docs.chain.link/docs/link-token-contracts/
    link_token: '0xa36085F69e2889c224210F603D836748e7dC0088'

    #https://docs.chain.link/docs/vrf-contracts/v1/#kovan
    keyhash: '0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4'
    fee: 100000000000000000
    verify: False
    
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}